import Foundation

enum RecordIconRecipeFactory {
    static func makeRecipe(title: String, artist: String) -> RecordIconRecipe {
        let seed = normalizedSeed(title: title, artist: artist)
        let hash = fnv1a(seed)

        let baseColors = VinylColorToken.allCases.filter { $0 != .navy }
        let labelColors = [VinylColorToken.cream, .butter, .sky, .mint]
        let accentColors = [VinylColorToken.navy, .coral, .lilac]

        return RecordIconRecipe(
            baseColor: baseColors[hash % baseColors.count],
            labelColor: labelColors[(hash / 7) % labelColors.count],
            accentColor: accentColors[(hash / 13) % accentColors.count],
            pattern: RecordPatternPreset.allCases[(hash / 17) % RecordPatternPreset.allCases.count],
            isAutoGenerated: true
        )
    }

    static func normalizedSeed(title: String, artist: String) -> String {
        "\(normalize(title))|\(normalize(artist))"
    }

    private static func normalize(_ value: String) -> String {
        value
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
            .lowercased()
    }

    private static func fnv1a(_ value: String) -> Int {
        var hash: UInt64 = 1469598103934665603
        let prime: UInt64 = 1099511628211

        for scalar in value.unicodeScalars {
            hash ^= UInt64(scalar.value)
            hash = hash &* prime
        }

        return Int(hash % UInt64(Int.max))
    }
}

