import SwiftData
import SwiftUI

struct RecordDetailView: View {
    @Environment(\.appThemePalette) private var palette
    @Environment(\.appFontPreset) private var fontPreset
    @Environment(\.modelContext) private var modelContext
    @Query private var settings: [AppSettings]
    @Query private var profiles: [LibraryRecordProfile]
    @State private var isEditing = false
    @GestureState private var dragOffset: CGFloat = 0

    let record: RecordItem
    let onClose: () -> Void

    var body: some View {
        GeometryReader { proxy in
            ZStack(alignment: .bottom) {
                Color.black.opacity(backdropOpacity)
                    .ignoresSafeArea()
                    .contentShape(Rectangle())
                    .onTapGesture(perform: onClose)

                detailSurface(height: proxy.size.height)
                    .offset(y: max(0, dragOffset))
                    .gesture(dismissGesture)
            }
            .ignoresSafeArea(edges: .bottom)
        }
        .sheet(isPresented: $isEditing) {
            EditRecordView(record: record)
        }
    }

    private func detailSurface(height: CGFloat) -> some View {
        let presentation = RecordLibraryPresentation(record: record, profile: activeProfile)

        return VStack(spacing: 0) {
            topBar

            ScrollView {
                VStack(alignment: .leading, spacing: AppTheme.sectionSpacing) {
                    HStack(alignment: .top, spacing: 18) {
                        RecordArtworkView(recipe: record.iconRecipe, size: 132)

                        VStack(alignment: .leading, spacing: 8) {
                            Text(presentation.snapshot.title)
                                .font(fontPreset.font(size: 28, weight: .bold))
                                .foregroundStyle(palette.textPrimary)

                            if let subtitle = presentation.snapshot.subtitle {
                                Text(subtitle)
                                    .font(fontPreset.textStyle(.title3))
                                    .foregroundStyle(palette.textSecondary)
                            }

                            if presentation.showsRating && settings.first?.preferredRatingStyle ?? .stars == .stars {
                                StarRatingView(
                                    ratingValue: record.ratingValue,
                                    size: 14,
                                    activeColor: palette.textPrimary,
                                    inactiveColor: palette.textSecondary
                                )
                            } else if presentation.showsRating {
                                Text(ratingText)
                                    .font(fontPreset.textStyle(.caption))
                                    .foregroundStyle(palette.textPrimary)
                            }
                        }
                    }
                    .cardSurface(palette.secondaryBackground)

                    VStack(alignment: .leading, spacing: 10) {
                        ForEach(Array(presentation.allDetails.enumerated()), id: \.offset) { _, detail in
                            detailRow(detail.0, value: detail.1)
                        }
                        detailRow("Added", value: addedText)
                        detailRow("Icon", value: record.iconRecipe.isAutoGenerated ? "Auto" : "Custom")
                    }
                    .cardSurface(palette.surfaceButter)

                    VStack(alignment: .leading, spacing: 10) {
                        Text(record.notes.isEmpty ? "—" : record.notes)
                            .font(fontPreset.textStyle(.body))
                            .foregroundStyle(record.notes.isEmpty ? palette.textSecondary : palette.textPrimary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .cardSurface(palette.surfaceSky)

                    if presentation.showsTags {
                        VStack(alignment: .leading, spacing: 10) {
                            if record.tags.isEmpty {
                                Text("—")
                                    .foregroundStyle(palette.textSecondary)
                            } else {
                                FlowTagLayout(tags: record.tags)
                            }
                        }
                        .cardSurface(palette.surfaceMint)
                    }

                    Button(role: .destructive) {
                        RecordEditor.delete(record: record, in: modelContext)
                        onClose()
                    } label: {
                        Text("Delete")
                            .font(fontPreset.textStyle(.headline, weight: .semibold))
                            .frame(maxWidth: .infinity)
                    }
                    .padding(.vertical, 16)
                    .background(
                        RoundedRectangle(cornerRadius: AppTheme.cardRadius, style: .continuous)
                            .fill(Color.red.opacity(0.12))
                    )
                }
                .padding(AppTheme.outerPadding)
                .padding(.bottom, 18)
            }
            .scrollIndicators(.hidden)
        }
        .frame(maxWidth: .infinity)
        .frame(height: height * 0.9, alignment: .top)
        .background(
            RoundedRectangle(cornerRadius: 34, style: .continuous)
                .fill(palette.background)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 34, style: .continuous)
                .stroke(palette.line.opacity(0.6), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.14), radius: 28, y: -8)
    }

    private var topBar: some View {
        VStack(spacing: 12) {
            Capsule(style: .continuous)
                .fill(palette.line)
                .frame(width: 52, height: 6)
                .padding(.top, 12)

            HStack {
                Button("Done", action: onClose)
                    .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                    .foregroundStyle(palette.textSecondary)

                Spacer()

                Text("")
                    .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                    .foregroundStyle(palette.textSecondary)

                Spacer()

                Button("Edit") {
                    isEditing = true
                }
                .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                .foregroundStyle(palette.textPrimary)
            }
            .padding(.horizontal, AppTheme.outerPadding)
            .padding(.bottom, 4)
        }
    }

    private func detailRow(_ title: String, value: String) -> some View {
        HStack {
            Text(title)
                .foregroundStyle(palette.textSecondary)
            Spacer()
            Text(value)
                .foregroundStyle(palette.textPrimary)
        }
        .font(fontPreset.textStyle(.subheadline))
    }

    private var dismissGesture: some Gesture {
        DragGesture(minimumDistance: 8)
            .updating($dragOffset) { value, state, _ in
                guard value.translation.height > 0 else { return }
                state = value.translation.height
            }
            .onEnded { value in
                if value.translation.height > 140 || value.predictedEndTranslation.height > 220 {
                    onClose()
                }
            }
    }

    private var backdropOpacity: Double {
        let progress = min(max(dragOffset / 220, 0), 1)
        return 0.18 * (1 - progress)
    }

    private var ratingText: String {
        StarRatingValue.tenPointLabel(for: record.ratingValue)
    }

    private var addedText: String {
        record.createdAt.formatted(date: .abbreviated, time: .omitted)
    }

    private var activeProfile: LibraryRecordProfile? {
        profiles.first(where: { $0.record.persistentModelID == record.persistentModelID })
    }
}

private struct FlowTagLayout: View {
    let tags: [Tag]

    var body: some View {
        LazyVGrid(columns: [GridItem(.adaptive(minimum: 80), spacing: 8)], alignment: .leading, spacing: 8) {
            ForEach(tags, id: \.persistentModelID) { tag in
                TagChipView(title: tag.name, colorToken: tag.colorToken)
            }
        }
    }
}
