import SwiftData
import SwiftUI

struct RecordDetailView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Query private var settings: [AppSettings]
    @State private var isEditing = false
    let record: RecordItem

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: AppTheme.sectionSpacing) {
                    HStack(alignment: .top, spacing: 18) {
                        RecordArtworkView(recipe: record.iconRecipe, size: 132)

                        VStack(alignment: .leading, spacing: 8) {
                            Text(record.title)
                                .font(.system(size: 28, weight: .bold, design: .rounded))
                                .foregroundStyle(AppTheme.textPrimary)

                            Text(record.artist)
                                .font(.title3)
                                .foregroundStyle(AppTheme.textSecondary)

                            Text(ratingText)
                                .font(.subheadline.weight(.semibold))
                                .foregroundStyle(AppTheme.textPrimary)
                        }
                    }
                    .cardSurface(AppTheme.secondaryBackground)

                    VStack(alignment: .leading, spacing: 10) {
                        Text("Details")
                            .font(.headline)
                        detailRow("Genre", value: record.genre.isEmpty ? "None" : record.genre)
                        detailRow("Release Year", value: record.releaseYear.map(String.init) ?? "Unknown")
                        detailRow("Icon Mode", value: record.iconRecipe.isAutoGenerated ? "Auto-generated" : "Custom preset")
                    }
                    .cardSurface(AppTheme.surfaceButter)

                    VStack(alignment: .leading, spacing: 10) {
                        Text("Notes")
                            .font(.headline)
                        Text(record.notes.isEmpty ? "No notes yet." : record.notes)
                            .font(.body)
                            .foregroundStyle(record.notes.isEmpty ? AppTheme.textSecondary : AppTheme.textPrimary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .cardSurface(AppTheme.surfaceSky)

                    VStack(alignment: .leading, spacing: 10) {
                        Text("Tags")
                            .font(.headline)
                        if record.tags.isEmpty {
                            Text("No tags yet.")
                                .foregroundStyle(AppTheme.textSecondary)
                        } else {
                            FlowTagLayout(tags: record.tags)
                        }
                    }
                    .cardSurface(AppTheme.surfaceMint)

                    Button(role: .destructive) {
                        RecordEditor.delete(record: record, in: modelContext)
                        dismiss()
                    } label: {
                        Text("Delete Record")
                            .font(.headline)
                            .frame(maxWidth: .infinity)
                    }
                    .padding(.vertical, 16)
                    .background(
                        RoundedRectangle(cornerRadius: AppTheme.cardRadius, style: .continuous)
                            .fill(Color.red.opacity(0.12))
                    )
                }
                .padding(AppTheme.outerPadding)
            }
            .background(AppTheme.background)
            .navigationTitle("Record")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Close") { dismiss() }
                }
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Edit") { isEditing = true }
                }
            }
            .sheet(isPresented: $isEditing) {
                EditRecordView(record: record)
            }
        }
    }

    private func detailRow(_ title: String, value: String) -> some View {
        HStack {
            Text(title)
                .foregroundStyle(AppTheme.textSecondary)
            Spacer()
            Text(value)
                .foregroundStyle(AppTheme.textPrimary)
        }
        .font(.subheadline)
    }

    private var ratingText: String {
        switch settings.first?.preferredRatingStyle ?? .stars {
        case .stars:
            let stars = max(1, Int(round(Double(record.ratingValue) / 2.0)))
            return String(repeating: "★", count: stars)
        case .tenPoint:
            return "\(record.ratingValue)/10"
        }
    }
}

private struct FlowTagLayout: View {
    let tags: [Tag]

    var body: some View {
        LazyVGrid(columns: [GridItem(.adaptive(minimum: 80), spacing: 8)], alignment: .leading, spacing: 8) {
            ForEach(tags, id: \.persistentModelID) { tag in
                TagChipView(title: tag.name, colorToken: tag.colorToken)
            }
        }
    }
}

