import SwiftData
import SwiftUI

struct RecordDetailView: View {
    @Environment(\.modelContext) private var modelContext
    @Query private var settings: [AppSettings]
    @State private var isEditing = false
    @GestureState private var dragOffset: CGFloat = 0

    let record: RecordItem
    let onClose: () -> Void

    var body: some View {
        GeometryReader { proxy in
            ZStack(alignment: .bottom) {
                Color.black.opacity(backdropOpacity)
                    .ignoresSafeArea()
                    .contentShape(Rectangle())
                    .onTapGesture(perform: onClose)

                detailSurface(height: proxy.size.height)
                    .offset(y: max(0, dragOffset))
                    .gesture(dismissGesture)
            }
            .ignoresSafeArea(edges: .bottom)
        }
        .sheet(isPresented: $isEditing) {
            EditRecordView(record: record)
        }
    }

    private func detailSurface(height: CGFloat) -> some View {
        VStack(spacing: 0) {
            topBar

            ScrollView {
                VStack(alignment: .leading, spacing: AppTheme.sectionSpacing) {
                    HStack(alignment: .top, spacing: 18) {
                        RecordArtworkView(recipe: record.iconRecipe, size: 132)

                        VStack(alignment: .leading, spacing: 8) {
                            Text(record.title)
                                .font(.system(size: 28, weight: .bold, design: .rounded))
                                .foregroundStyle(AppTheme.textPrimary)

                            Text(record.artist)
                                .font(.title3)
                                .foregroundStyle(AppTheme.textSecondary)

                            Text(ratingText)
                                .font(.subheadline.weight(.semibold))
                                .foregroundStyle(AppTheme.textPrimary)
                        }
                    }
                    .cardSurface(AppTheme.secondaryBackground)

                    VStack(alignment: .leading, spacing: 10) {
                        detailRow("Genre", value: record.genre.isEmpty ? "—" : record.genre)
                        detailRow("Year", value: record.releaseYear.map(String.init) ?? "—")
                        detailRow("Icon", value: record.iconRecipe.isAutoGenerated ? "Auto" : "Custom")
                    }
                    .cardSurface(AppTheme.surfaceButter)

                    VStack(alignment: .leading, spacing: 10) {
                        Text(record.notes.isEmpty ? "—" : record.notes)
                            .font(.body)
                            .foregroundStyle(record.notes.isEmpty ? AppTheme.textSecondary : AppTheme.textPrimary)
                    }
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .cardSurface(AppTheme.surfaceSky)

                    VStack(alignment: .leading, spacing: 10) {
                        if record.tags.isEmpty {
                            Text("—")
                                .foregroundStyle(AppTheme.textSecondary)
                        } else {
                            FlowTagLayout(tags: record.tags)
                        }
                    }
                    .cardSurface(AppTheme.surfaceMint)

                    Button(role: .destructive) {
                        RecordEditor.delete(record: record, in: modelContext)
                        onClose()
                    } label: {
                        Text("Delete")
                            .font(.headline)
                            .frame(maxWidth: .infinity)
                    }
                    .padding(.vertical, 16)
                    .background(
                        RoundedRectangle(cornerRadius: AppTheme.cardRadius, style: .continuous)
                            .fill(Color.red.opacity(0.12))
                    )
                }
                .padding(AppTheme.outerPadding)
                .padding(.bottom, 18)
            }
            .scrollIndicators(.hidden)
        }
        .frame(maxWidth: .infinity)
        .frame(height: height * 0.9, alignment: .top)
        .background(
            RoundedRectangle(cornerRadius: 34, style: .continuous)
                .fill(AppTheme.background)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 34, style: .continuous)
                .stroke(AppTheme.line.opacity(0.6), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.14), radius: 28, y: -8)
    }

    private var topBar: some View {
        VStack(spacing: 12) {
            Capsule(style: .continuous)
                .fill(AppTheme.line)
                .frame(width: 52, height: 6)
                .padding(.top, 12)

            HStack {
                Button("Done", action: onClose)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(AppTheme.textSecondary)

                Spacer()

                Text("")
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(AppTheme.textSecondary)

                Spacer()

                Button("Edit") {
                    isEditing = true
                }
                .font(.subheadline.weight(.semibold))
                .foregroundStyle(AppTheme.textPrimary)
            }
            .padding(.horizontal, AppTheme.outerPadding)
            .padding(.bottom, 4)
        }
    }

    private func detailRow(_ title: String, value: String) -> some View {
        HStack {
            Text(title)
                .foregroundStyle(AppTheme.textSecondary)
            Spacer()
            Text(value)
                .foregroundStyle(AppTheme.textPrimary)
        }
        .font(.subheadline)
    }

    private var dismissGesture: some Gesture {
        DragGesture(minimumDistance: 8)
            .updating($dragOffset) { value, state, _ in
                guard value.translation.height > 0 else { return }
                state = value.translation.height
            }
            .onEnded { value in
                if value.translation.height > 140 || value.predictedEndTranslation.height > 220 {
                    onClose()
                }
            }
    }

    private var backdropOpacity: Double {
        let progress = min(max(dragOffset / 220, 0), 1)
        return 0.18 * (1 - progress)
    }

    private var ratingText: String {
        switch settings.first?.preferredRatingStyle ?? .stars {
        case .stars:
            let stars = max(1, Int(round(Double(record.ratingValue) / 2.0)))
            return String(repeating: "★", count: stars)
        case .tenPoint:
            return "\(record.ratingValue)/10"
        }
    }
}

private struct FlowTagLayout: View {
    let tags: [Tag]

    var body: some View {
        LazyVGrid(columns: [GridItem(.adaptive(minimum: 80), spacing: 8)], alignment: .leading, spacing: 8) {
            ForEach(tags, id: \.persistentModelID) { tag in
                TagChipView(title: tag.name, colorToken: tag.colorToken)
            }
        }
    }
}
