import UIKit
import SwiftUI

struct RecordFormView: View {
    let title: String
    let saveButtonTitle: String
    let ratingStyle: RatingStyle
    @Binding var draft: RecordDraft
    let onSave: () -> Void

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: AppTheme.sectionSpacing) {
                if !title.isEmpty {
                    PageSectionHeader(
                        eyebrow: "",
                        title: title,
                        subtitle: ""
                    )
                }

                detailsSection
                ratingSection
                iconSection
                notesSection

                Button(action: onSave) {
                    Text(saveButtonTitle)
                        .font(.headline)
                        .foregroundStyle(Color.white)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 16)
                        .background(
                            RoundedRectangle(cornerRadius: 20, style: .continuous)
                                .fill(AppTheme.textPrimary)
                        )
                }
                .buttonStyle(.plain)
                .disabled(!draft.canSave)
                .opacity(draft.canSave ? 1 : 0.5)
            }
            .padding(AppTheme.outerPadding)
        }
        .background(AppTheme.background)
        .scrollContentBackground(.hidden)
        .onChange(of: draft.title) { _, _ in refreshAutoIconIfNeeded() }
        .onChange(of: draft.artist) { _, _ in refreshAutoIconIfNeeded() }
    }

    private var detailsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            Group {
                textField("Title", text: $draft.title)
                textField("Artist", text: $draft.artist)
                textField("Year", text: $draft.releaseYearText, keyboardType: .numberPad)
                textField("Genre", text: $draft.genre)
                textField("Tags", text: $draft.tagsText)
            }
        }
        .cardSurface(AppTheme.surfaceRose)
    }

    private var ratingSection: some View {
        RatingControl(style: ratingStyle, ratingValue: $draft.ratingValue)
            .cardSurface(AppTheme.surfaceButter)
    }

    private var iconSection: some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack {
                Spacer()
                if !draft.iconRecipe.isAutoGenerated {
                    Button("Auto") {
                        draft.iconRecipe = RecordIconRecipeFactory.makeRecipe(title: draft.title, artist: draft.artist)
                    }
                    .font(.subheadline.weight(.semibold))
                }
            }

            HStack(spacing: 18) {
                RecordArtworkView(recipe: draft.iconRecipe, size: 110)

                VStack(alignment: .leading, spacing: 12) {
                    tokenPicker("Base", selection: Binding(
                        get: { draft.iconRecipe.baseColor },
                        set: { draft.iconRecipe.baseColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                    tokenPicker("Label", selection: Binding(
                        get: { draft.iconRecipe.labelColor },
                        set: { draft.iconRecipe.labelColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                    tokenPicker("Accent", selection: Binding(
                        get: { draft.iconRecipe.accentColor },
                        set: { draft.iconRecipe.accentColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Picker("Pattern", selection: Binding(
                    get: { draft.iconRecipe.pattern },
                    set: { draft.iconRecipe.pattern = $0; draft.iconRecipe.isAutoGenerated = false }
                )) {
                    ForEach(RecordPatternPreset.allCases) { pattern in
                        Text(pattern.title).tag(pattern)
                    }
                }
                .pickerStyle(.segmented)
            }
        }
        .cardSurface(AppTheme.surfaceMint)
    }

    private var notesSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            TextField("Notes", text: $draft.notes, axis: .vertical)
                .lineLimit(4...8)
                .padding(14)
                .background(
                    RoundedRectangle(cornerRadius: AppTheme.innerRadius, style: .continuous)
                        .fill(AppTheme.secondaryBackground)
                )
        }
        .cardSurface(AppTheme.surfaceSky)
    }

    private func textField(_ title: String, text: Binding<String>, prompt: String? = nil, keyboardType: UIKeyboardType = .default) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            TextField(prompt ?? title, text: text)
                .keyboardType(keyboardType)
                .textInputAutocapitalization(.words)
                .padding(14)
                .background(
                    RoundedRectangle(cornerRadius: AppTheme.innerRadius, style: .continuous)
                        .fill(AppTheme.secondaryBackground)
                )
        }
    }

    private func tokenPicker(_ title: String, selection: Binding<VinylColorToken>) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Picker(title, selection: selection) {
                ForEach(VinylColorToken.allCases) { token in
                    Text(token.rawValue.capitalized).tag(token)
                }
            }
            .pickerStyle(.menu)
        }
    }

    private func refreshAutoIconIfNeeded() {
        guard draft.iconRecipe.isAutoGenerated else { return }
        draft.iconRecipe = RecordIconRecipeFactory.makeRecipe(title: draft.title, artist: draft.artist)
    }
}
