import Foundation

struct RecordIconRecipe: Codable, Equatable {
    var baseColor: VinylColorToken
    var labelColor: VinylColorToken
    var accentColor: VinylColorToken
    var pattern: RecordPatternPreset
    var isAutoGenerated: Bool
}

