import UIKit
import SwiftUI

struct RecordFormView: View {
    @Environment(\.appThemePalette) private var palette
    @Environment(\.appFontPreset) private var fontPreset
    let library: Library
    let title: String
    let saveButtonTitle: String
    let ratingStyle: RatingStyle
    @Binding var draft: RecordDraft
    let onSave: () -> Void

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: AppTheme.sectionSpacing) {
                if !title.isEmpty {
                    PageSectionHeader(
                        eyebrow: "",
                        title: title,
                        subtitle: ""
                    )
                }

                detailsSection
                ratingSection
                iconSection
                notesSection

                Button(action: onSave) {
                    Text(saveButtonTitle)
                        .font(fontPreset.textStyle(.headline, weight: .semibold))
                        .foregroundStyle(palette.accentContent)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 16)
                        .background(
                            RoundedRectangle(cornerRadius: 20, style: .continuous)
                                .fill(palette.accentFill)
                        )
                }
                .buttonStyle(.plain)
                .disabled(!draft.canSave)
                .opacity(draft.canSave ? 1 : 0.5)
            }
            .padding(AppTheme.outerPadding)
        }
        .background(palette.background)
        .scrollContentBackground(.hidden)
        .onChange(of: draft.primaryTitle) { _, _ in refreshAutoIconIfNeeded() }
        .onChange(of: draft.secondaryTitle) { _, _ in refreshAutoIconIfNeeded() }
    }

    private var detailsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            ForEach(library.fieldDefinitions) { field in
                dynamicField(field)
            }

            textField("Tags", text: $draft.tagsText)
        }
        .cardSurface(palette.surfaceRose)
    }

    private var ratingSection: some View {
        RatingControl(style: ratingStyle, ratingValue: $draft.ratingValue)
            .cardSurface(palette.surfaceButter)
    }

    private var iconSection: some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack {
                Spacer()
                if !draft.iconRecipe.isAutoGenerated {
                    Button("Auto") {
                        draft.iconRecipe = RecordIconRecipeFactory.makeRecipe(title: draft.primaryTitle, artist: draft.secondaryTitle)
                    }
                    .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                }
            }

            HStack(spacing: 18) {
                RecordArtworkView(recipe: draft.iconRecipe, size: 110)

                VStack(alignment: .leading, spacing: 12) {
                    tokenPicker("Base", selection: Binding(
                        get: { draft.iconRecipe.baseColor },
                        set: { draft.iconRecipe.baseColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                    tokenPicker("Label", selection: Binding(
                        get: { draft.iconRecipe.labelColor },
                        set: { draft.iconRecipe.labelColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                    tokenPicker("Accent", selection: Binding(
                        get: { draft.iconRecipe.accentColor },
                        set: { draft.iconRecipe.accentColor = $0; draft.iconRecipe.isAutoGenerated = false }
                    ))
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Picker("Pattern", selection: Binding(
                    get: { draft.iconRecipe.pattern },
                    set: { draft.iconRecipe.pattern = $0; draft.iconRecipe.isAutoGenerated = false }
                )) {
                    ForEach(RecordPatternPreset.allCases) { pattern in
                        Text(pattern.title).tag(pattern)
                    }
                }
                .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                .pickerStyle(.segmented)
            }
        }
        .cardSurface(palette.surfaceMint)
    }

    private var notesSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            TextField("Notes", text: $draft.notes, axis: .vertical)
                .lineLimit(4...8)
                .padding(14)
                .background(
                    RoundedRectangle(cornerRadius: AppTheme.innerRadius, style: .continuous)
                        .fill(palette.secondaryBackground)
                )
        }
        .cardSurface(palette.surfaceSky)
    }

    private func dynamicField(_ field: LibraryFieldDefinition) -> some View {
        textField(
            field.label,
            text: Binding(
                get: { draft.value(for: field.id) },
                set: { draft.setValue($0, for: field.id) }
            ),
            keyboardType: keyboardType(for: field.type)
        )
    }

    private func textField(_ title: String, text: Binding<String>, prompt: String? = nil, keyboardType: UIKeyboardType = .default) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title)
                .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                .foregroundStyle(palette.textPrimary)

            TextField(prompt ?? title, text: text)
                .font(fontPreset.textStyle(.body))
                .keyboardType(keyboardType)
                .textInputAutocapitalization(.words)
                .padding(14)
                .background(
                    RoundedRectangle(cornerRadius: AppTheme.innerRadius, style: .continuous)
                        .fill(palette.secondaryBackground)
                )
        }
    }

    private func tokenPicker(_ title: String, selection: Binding<VinylColorToken>) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title)
                .font(fontPreset.textStyle(.subheadline, weight: .semibold))
                .foregroundStyle(palette.textPrimary)

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 88), spacing: 8)], spacing: 8) {
                ForEach(VinylColorToken.allCases) { token in
                    Button {
                        selection.wrappedValue = token
                    } label: {
                        HStack(spacing: 8) {
                            Circle()
                                .fill(token.color)
                                .frame(width: 14, height: 14)

                            Text(token.title)
                                .font(fontPreset.textStyle(.caption, weight: .semibold))
                                .foregroundStyle(selection.wrappedValue == token ? palette.accentContent : palette.textPrimary)
                        }
                        .frame(maxWidth: .infinity)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 10)
                        .background(
                            RoundedRectangle(cornerRadius: 14, style: .continuous)
                                .fill(selection.wrappedValue == token ? palette.accentFill : palette.secondaryBackground)
                        )
                        .overlay(
                            RoundedRectangle(cornerRadius: 14, style: .continuous)
                                .stroke(
                                    selection.wrappedValue == token ? palette.accentFill : palette.line.opacity(0.7),
                                    lineWidth: selection.wrappedValue == token ? 2 : 1
                                )
                        )
                    }
                    .buttonStyle(.plain)
                }
            }
        }
    }

    private func keyboardType(for type: LibraryFieldType) -> UIKeyboardType {
        switch type {
        case .text:
            return .default
        case .number:
            return .numberPad
        case .date:
            return .numbersAndPunctuation
        }
    }

    private func refreshAutoIconIfNeeded() {
        guard draft.iconRecipe.isAutoGenerated else { return }
        draft.iconRecipe = RecordIconRecipeFactory.makeRecipe(title: draft.primaryTitle, artist: draft.secondaryTitle)
    }
}
