import Foundation
import SwiftData

@Model
final class RecordItem {
    var title: String
    var artist: String
    var releaseYear: Int?
    var genre: String
    var ratingValue: Int
    var notes: String
    var createdAt: Date
    var updatedAt: Date
    var iconBaseColorRawValue: String
    var iconLabelColorRawValue: String
    var iconAccentColorRawValue: String
    var iconPatternRawValue: String
    var iconIsAutoGenerated: Bool
    @Relationship var tags: [Tag]

    init(
        title: String,
        artist: String,
        releaseYear: Int? = nil,
        genre: String = "",
        ratingValue: Int = 8,
        notes: String = "",
        iconRecipe: RecordIconRecipe,
        tags: [Tag] = []
    ) {
        self.title = title
        self.artist = artist
        self.releaseYear = releaseYear
        self.genre = genre
        self.ratingValue = ratingValue
        self.notes = notes
        self.createdAt = .now
        self.updatedAt = .now
        self.iconBaseColorRawValue = iconRecipe.baseColor.rawValue
        self.iconLabelColorRawValue = iconRecipe.labelColor.rawValue
        self.iconAccentColorRawValue = iconRecipe.accentColor.rawValue
        self.iconPatternRawValue = iconRecipe.pattern.rawValue
        self.iconIsAutoGenerated = iconRecipe.isAutoGenerated
        self.tags = tags
    }

    var iconRecipe: RecordIconRecipe {
        get {
            RecordIconRecipe(
                baseColor: VinylColorToken(rawValue: iconBaseColorRawValue) ?? .peach,
                labelColor: VinylColorToken(rawValue: iconLabelColorRawValue) ?? .cream,
                accentColor: VinylColorToken(rawValue: iconAccentColorRawValue) ?? .navy,
                pattern: RecordPatternPreset(rawValue: iconPatternRawValue) ?? .rings,
                isAutoGenerated: iconIsAutoGenerated
            )
        }
        set {
            iconBaseColorRawValue = newValue.baseColor.rawValue
            iconLabelColorRawValue = newValue.labelColor.rawValue
            iconAccentColorRawValue = newValue.accentColor.rawValue
            iconPatternRawValue = newValue.pattern.rawValue
            iconIsAutoGenerated = newValue.isAutoGenerated
        }
    }
}

